### ISSUE TITLE
NoClassDefFound when clicking the Planner in Tinker Station

### ISSUE THREAD

**Issue by Raidobw2** [tiffit/tconplanner#1]
### Issue Description
Hi! Looks like I'm first!😊 I understand your mod integrates Tinker's Construct. There's a NoClassDefFoundError on clients when clicking the Planner in the Tinker Station. They might have done file reorganization, and you'll need to reintegrate it, that's my wild guess.

### Versions
Minecraft: 1.16.5
Forge: 36.2.9
Modpack and version: FTB OceanBlock v1.7.0
Tinker's Construct: TConstruct-1.16.5-3.2.0.290.jar
Mantle: Mantle-1.16.5-1.6.127.jar
TConPlanner: tconplanner-1.16.5-1.1.0.jar

### Steps to reproduce
Play with those mod files or with FTB OceanBlock v1.7.0.
Place down a Tinker Station.
Click the Planner icon.
Crash to desktop, exit code -1, client crash, NoClassDefFoundError.

### Logs
My crash-report to simplify reading: https://paste.feed-the-beast.com/view/823ebd00
`latest.log` from user: https://paste.ee/p/oEx1X

### Other
Thanks for making this mod and best wishes in development for you and your mod!

**Comment by tiffit** [comment]
Thank you for the report! Seems like tcon devs made a lot of internal changes. I’ll work on an update that works with the new version

**Comment by tiffit** [comment]
Tinker's Planner 1.1.1 should fix this issue

**Comment by Raidobw2** [comment]
Thank you very much and have a good day!
