### ISSUE TITLE
[Crash // 1.18.2 - 1.2.0] Crash from opening the Tool Planner Menu from a Tinkers' Construct Anvil

### ISSUE THREAD

**Issue by FocalFlare** [tiffit/tconplanner#13]
_Recently, my game started crashing just from opening the tool planner from an anvil. The crash thankfully didn't result in a temporary infinite loop crash affecting not just the world I tried this in but also every other world I tried to log into, forcing me to restart my game. Kinda weird because--despite not using it for quite a while--this mod was working perfectly fine._ 

_I've already looked at someone else having this same or if not a similar issue [#8], but for their case they were using this mod for 1.16.5 and a new version was made available to them at that time. For my case, 1.2.0 is sadly the only version available and hasn't had any newer versions. Hopefully it doesn't become abandoned!_

_I know this probably might be because I need to update Forge or whatever (which I've been a bit lazy on, but if it's because of any of my mods interfering with it, then it'll be a very tedious process to go through all of them 1-by-1 to see what's causing it. Again, this crash doesn't force me to relaunch my game manually. It just kicks me out of my world._

_Solutions for this crash might work for everyone who's having this same issue but are 100% not guaranteed to work for those with even a slightly different issue. Regardless, I appreciate your input(s)!_

### Version Info
- Minecraft 1.18.2
- Tinkers' Construct 3.7.1.155 [Forge]
- Tinkers' Planner 1.2.0 [Forge]
- Forge 40.2.17

### Steps to Reproduce
This was tested with a Tinkers' Construct anvil but it probably happens with the tool station as well.
1. Place down any anvil from **Tinkers' Construct**.
2. Right-click the anvil to open its menu.
3. Click the blueprint icon.

### Behaviors
- Expected: Open the tool planning menu.
- Actual: Crash my game.

### Crash report
[crash-2024-04-13_21.33.14-client.txt](https://github.com/tiffit/tconplanner/files/14969333/crash-2024-04-13_21.33.14-client.txt)

**Comment by FocalFlare** [comment]
_Update 4.25.24: Tested it with the Modrinth version of this mod, this time on the tool station. The crash happens with the tool station as well._

**Comment by FocalFlare** [comment]
_It's safe to say that this mod has been abandoned as there hasn't been any response to this issue for 3 weeks, but I won't manually close this issue as either completed or not planned. However, if closed and you still have any inputs, please feel free to respond with them so that this issue can be opened again._

**Comment by FocalFlare** [comment]
_I don't know if this was either **TConstructCompatible** or **Tinkers' Reforged** causing this crash, but I disabled both and I'm able to open the planner. I'll report back once I figure out which of these two mods is the culprit. However, this issue will stay open for the dev to provide their input._

**Comment by FocalFlare** [comment]
_A'ight seems like these two mods were causing this crash, though other similar mods could cause this crash as well._

**Comment by Panderine** [comment]
Had exact same crash. Don't have those 2 mods installed. :(

**Comment by FocalFlare** [comment]
> Had exact same crash. Don't have those 2 mods installed. :(

_I mean I don't know what the cause is, but I just disabled those two mods and the planner seemed to work fine for me afterwards._

_**If you'd like to reopen this issue, feel free. Otherwise, we're not getting a response from @tiffit anytime soon or at all on this issue. This issue will be closed as not planned, having took 3 months for a response from the developer of this mod.**_

**Comment by Proctopeo** [comment]
Having a similar crash that gives this error:
`java.lang.NoSuchMethodError: 'int slimeknights.tconstruct.library.recipe.modifiers.ModifierRecipeLookup.getNeededPerLevel(slimeknights.tconstruct.library.modifiers.ModifierId)'`
Neither of the TC submods I have installed seem to be responsible (Construct's Armory Port and Tinker's Rapier), nor do any of my other mods. I suspect that an update to the main Tinker's Construct mod made this one unstable, which is a shame.

Edit: Read your crash log, it does appear to be the same issue.
