### ISSUE TITLE
[Feature Request] "Recreate from Item" button

### ISSUE THREAD

**Issue by Apceniy** [tiffit/tconplanner#4]
It would be very convenient to have a way to input a tool I have in my inventory so I don't have to manually input every part and modifier (the opposite of the "Give Item" button). It would be useful, for example, when I want to know what else can I do with the tool I already have. It could be a button in the Tinker's Station/Anvil that would target the tool in the corresponding slot of the block, or in the planner itself, in which case it would target the tool in the hand.

**Comment by tiffit** [comment]
This is a planned feature. The button will only be able to import the tool parts and not the modifiers as the mod needs to know the order that modifiers are applied in order to do proper validation, something that can’t easily be taken from a tool’s NBT
