### ISSUE TITLE
[Feature Request] Open Planner keybind

### ISSUE THREAD

**Issue by Apceniy** [tiffit/tconplanner#5]
It would be convenient to have a keybind that would allow to open the planner without having to go to the Tinker's Station/Anvil.

**Comment by tiffit** [comment]
I want to keep the mod as something that you only need to deal with if you want to use it. Adding a new keybind, especially in an environment where key conflicts are very common, goes against this. I also find it more fitting to only be accessible from the tinker anvil/station.
