### ISSUE TITLE
[Feature Request] Armor planning

### ISSUE THREAD

**Issue by Apceniy** [tiffit/tconplanner#6]
Currently, Tinker's Planner only allows planning tools. But in Tinkers' Construct you can also apply modifiers to the armor, so it would be cool to plan armor as well. Moreover, the mod already shows defense stots, so it would make sense.

**Comment by tiffit** [comment]
From what I understand tools and armors are quite different internally. This would mean that the planner would require a major re-write for armor to work. The main feature of the planner is being able to see tool part combinations with modifiers being something extra. Maybe a planner for armor will come at some point but not anytime soon.
