### ISSUE TITLE
[Future Request] Update to 1.18

### ISSUE THREAD

**Issue by Cactusstudent** [tiffit/tconplanner#9]
Would you like to update this mod to 1.18, it's great.
(if not, i'm sorry to trouble you)

**Comment by RoboXGamer** [comment]
Me waiting too
Such a great mod!

**Comment by RoboXGamer** [comment]
still no eta when the mod is being updated

**Comment by tiffit** [comment]
Updated! 

https://www.curseforge.com/minecraft/mc-mods/tinkers-planner/files/4287330
